baseurl: https://algo.ulb.be/
title: Algorithms Research Group (ULB)
theme: hugo-creative-portfolio-theme
languageCode: en-us
# Enable comments by entering your Disqus shortname
#disqusShortname:
# Enable Google Analytics by entering your tracking code
#googleAnalytics:

sitemap:
  changefreq: monthly
  priority: 1

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: blue
  description: Website for the algo group @ ULB.
  #copyright:
  mobileNavAbout: >
    <b><a href="http://algo.ulb.be">Algorithms Research Group</a></b><br>
    <a href="http://www.ulb.ac.be/facs/sciences/info/index-en.html">Computer Science Department</a><br>
    <a href="http://www.ulb.ac.be/facs/sciences">Faculté des Sciences</a><br>
    <a href="http://www.ulb.ac.be">Université libre de Bruxelles (ULB)</a><br>
    Campus de la Plaine, CP 212<br>
    B-1050 Brussels, Belgium<br>
  sidebarAbout:
    - >
      <b><a href="http://algo.ulb.be">Algorithms Research Group</a></b><br>
      <a href="http://www.ulb.ac.be/facs/sciences/info/index-en.html">Computer Science Department</a><br>
      <a href="http://www.ulb.ac.be/facs/sciences">Faculté des Sciences</a><br>
      <a href="http://www.ulb.ac.be">Université libre de Bruxelles (ULB)</a><br>
      Campus de la Plaine, CP 212<br>
      B-1050 Brussels, Belgium<br>
    - >
        <img src="/img/delaunay.png" alt="" class="img-responsive">
    - >
      Keywords: Discrete and computational geometry,
      algorithmic and structural graph theory,
      combinatorial optimization, data structures.
    #- >
      #Currently funded research projects:
      #EUROCORES EuroGIGA <a href="http://eurogiga-compose.eu/about.php">ComPoSe</a> and
      #<a href="http://eurogiga.inf.fu-berlin.de/w/VORONOI/">VORONOI</a>,
      #and ARC <a href="http://www.ulb.ac.be/recherche/presentation/fr-arccerf.html">COPHYMA</a>.

  # Contact page
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #email:

  navlinks:
    # Nav links in the side bar
    - name: "The team"
      url: ""

    - name: "Alumni"
      url: "alumni/"

    - name: "Visitors"
      url: "visitors/"

  extlinks:
    # External nav links in the side bar
    - name: "Algo Lunch"
      url: "http://www.ulb.ac.be/di/algo/gjoret/algolunch.html"

  #social:
    #facebook:
    #googleplus:
    #email:
    #twitter:
    #linkedin:
    #stackoverflow:
    #instagram:
    #github:

  team:

    # Permanent staff

    - name: Jean Cardinal
      image: https://ipfs.io/ipfs/QmZDjVnsbfVp214pvFE9b8kzegSnTQm5e8wmuHAVPYPaM4
      webpage: http://homepages.ulb.ac.be/~jcardin
      description: Professor
      keywords: Discrete and computational geometry, graphs, information theory.
      office: 2.O8.112
      phone: 02/650.5608
      email: jcardin@ulb.ac.be

    - name: Samuel Fiorini
      image: https://ipfs.io/ipfs/Qmei2DJS3tiTFrRNu2Ak7pvfdEtK1bEu2JS4y48Xboxn41
      webpage: http://homepages.ulb.ac.be/~sfiorini
      description: Professor (Math Department)
      keywords: Combinatorial optimization, polyhedral combinatorics, graph theory.
      email: sfiorini@ulb.ac.be

    - name: Gwenaël Joret
      image: https://ipfs.io/ipfs/QmZjpp79XZy3sCv54RLpWLs4brGZPp28YuRo8D8HQnvdmj
      webpage: http://www.ulb.ac.be/di/algo/gjoret
      description: Assistant Professor
      keywords: Graph theory, combinatorial optimization, approximation algorithms.
      office: 2.O8.111
      phone: 02/650.5759
      email: gjoret@ulb.ac.be

    - name: Stefan Langerman
      image: https://ipfs.io/ipfs/Qmeyk7E5QHNiYFFCjpmPF9E1yv1tuFzjuf24WRtexCShvw
      webpage: https://algo.ulb.be/sl
      description: Directeur de recherches (FNRS Research Director)
      keywords: Computational geometry, data structures.
      office: 2.O8.113
      phone: 02/650.5928
      email: stefan.langerman@ulb.ac.be

    - name: John Iacono
      image: https://ipfs.io/ipfs/QmNjR3evqXzR1jzStoJNyVSTH1oKZfw9S54p9SWhAtQhAT
      webpage: http://johniacono.com
      description: Professor
      keywords: Data structures, computational geometry.
      office: 2.O8.114
      email: ulb@johniacono.com

    - name: Guy Louchard
      image: https://ipfs.io/ipfs/QmRPAFu7ChSKEvKqGFH6EjmGWc1wM43ivihw2hxEWiNsMW
      webpage: http://www.ulb.ac.be/di/mcs/louchard
      description: I am now retired so I can devote (almost) all my time to research.
      keywords: Probabilistic techniques
      office: 2.N8.206
      phone: 02/650.5613
      email: louchard@ulb.ac.be

    # Postdocs

    - name: Varunkumar Jayapaul
      description: Postdoc
      image: https://ipfs.io/ipfs/QmWUtxni81MPLgc7CGNWgs8KjkYkdMfQWiV28bWBuKCpt9
      office: 2.O8.214
      email: varunkumarj@gmail.com

    - name: Suman Bala
      description: Postdoc (Algo & QualSec)
      image: https://ipfs.io/ipfs/QmZcjkp6ovBS8VyZgS1Yk5b6WtLA2PFGebcGtsjhJMYnjf
      email: suman1005@gmail.com

    - name: Wouter Cames van Batenburg
      image: https://ipfs.io/ipfs/QmNycDvxe1WXd2prsmJjLMggrnSFj8LSz3hDY35jRQ5ARB
      webpage: http://homepages.ulb.ac.be/~wcamesva/
      description: Postdoc
      keywords: extremal combinatorics, percolation, colouring and packing of graphs.
      office: 2.O8.110

    - name: Grigorios Koumoutsos
      description: Postdoc
      image: https://ipfs.io/ipfs/QmVZ8VgLCg3yp9XrWmLW4NM79n8yww53wLDvq8Z9c2FVoh
      webpage: https://www.win.tue.nl/~gkoumout
      office: 2.O8.110

    - name: Ben Karsin
      description: Postdoc
      image: https://ipfs.io/ipfs/QmX8t9yEZNuTPRcco7sQPtkJZKMeS2esXZrbtybDAAg5gR
      webpage: https://benkarsin.com
      office: 2.O8.214

    - name: Tony Huynh
      description: Postdoc (Math Department)
      image: https://ipfs.io/ipfs/QmNUQQReJSnbYWJQq27LpHSuew31p1dwh1hkY9a2pxxHDR
      webpage: https://sites.google.com/site/matroidintersection

    - name: Krystal Guo
      description: Postdoc (Math Department)
      image: https://ipfs.io/ipfs/QmQGCmADK3HqhcjEpAJHcDGpQTnXSZJTz6o2H4aEgiGwgp
      webpage: https://simons.berkeley.edu/people/krystal-guo

    - name: Marco Macchia
      description: Postdoc. Former PhD student (Math Department).
      image: https://ipfs.io/ipfs/QmaMEk1Hxvu6FeNZav8qUsVZcngY2XZ25vwUTKA5bQgc6v
      webpage: http://homepages.ulb.ac.be/~mmacchia


    # PhD students

    - name: Keno Merckx
      image: https://ipfs.io/ipfs/QmWBYNC7pGAGJ3bf2NNQbM63yf8FDUtvi2uYtNvH3wx2sz
      webpage: http://homepages.ulb.ac.be/~kmerckx
      description: PhD student
      keywords: Graphs
      email: kmerckx@ulb.ac.be

    - name: Aurélien Ooms
      description: PhD student
      image: https://ipfs.io/ipfs/QmbHkqTGGg27ut2hyzwKp5asE8FxiHWaj5aiKxAsAWQdy6
      webpage: http://homepages.ulb.ac.be/~aureooms
      keywords: "Computational Complexity: Data Structures, Algorithms, Computational Geometry."
      office: 2.O8.214
      email: aureooms@ulb.ac.be

    - name: Carole Muller
      description: PhD student (Math Department)
      image: https://ipfs.io/ipfs/QmXBDYYmDnJKoC7o8uJPk5undF86AFmLKDNTgXP4QUfKEo
      webpage: http://student.ulb.ac.be/~camuller

    - name: Matthew Drescher
      description: PhD student (Math Department)
      image: https://ipfs.io/ipfs/Qmf94K9qs4n5UxMiAj63HTr1ofLwUKGXB35WTHVctaWaYe


    # External members

    - name: Sébastien Collette
      image: https://ipfs.io/ipfs/QmamQY7cPb4wB8ujAoQkv74aHrVuTT84R9YsyCdzeLqahn
      webpage: http://www.ulb.ac.be/di/algo/secollet
      description: Visiting professor (Maître de Conférence) at ULB. Consultant at Synapsis.
      keywords: Computational geometry, data structures.
      email: sebastien.collette@ulb.ac.be


  alumni:

    - name: Tillmann Miltzow
      image: https://ipfs.io/ipfs/QmXoDkSEedaADujsujchMmW94xQuM54fKnHbybfqocXJT4
      webpage: https://sites.google.com/site/tillshome
      description: Former Postdoc (Algo group and Math Department). Researcher at [Utrecht University](https://www.uu.nl/en).
      keywords: Computational geometry.
      email: t.miltzow@googlemail.com

    - name: Elena Arseneva (Khramtcova)
      image: https://ipfs.io/ipfs/QmV1kFnhP9Lpjy3bogEgrxxKamUmecdNBmiXesuNc8wKTH
      webpage: http://homepages.ulb.ac.be/~ekhramtc
      description: >
        Assistant Professor (старший преподаватель) in the Mathematics and TCS
        Program of [St. Petersburg State University](http://english.spbu.ru),
        Russia.
        Former Postdoc.
      keywords: Computational Geometry, Algorithms, Data Structures, Voronoi diagrams.
      email: elena.khramtsova@gmail.com

    - name: Udo Hoffmann
      image: https://ipfs.io/ipfs/QmcmaEVCXNSWskkQZ4fL7kz3zRL7q5B7MhXxhb8fmHngY2
      webpage: https://udohoffmann.bitbucket.io
      description: Former Postdoc
      keywords: Combinatorial geometry.
      email: udo.hoffmann@ulb.ac.be

    - name: Irina Kostitsyna
      image: https://ipfs.io/ipfs/QmUTzAJowiQtXTyC1GmeegZcvMzVzUGey5pmNXUczAyiEE
      webpage: http://homepages.ulb.ac.be/~ikostits
      description: >
        Assistant professor in the Applied Geometric Algorithms
        group at the Department of Mathematics and Computer Science at
        [TU Eindhoven](https://www.tue.nl/en). Former Postdoc.
      keywords: "Computational Geometry: Polygons."
      email: irina.kostitsyna@ulb.ac.be

    - name: Andrew Winslow
      description: >
        Assistant Professor at the [Computer Science
        Department](http://www.utrgv.edu/csci) at the [University of Texas Rio
        Grande Valley](http://www.utrgv.edu). Former Postdoc.
      webpage: http://andrewwinslow.com
      email: andrew.winslow+ulb@gmail.com
      image: https://ipfs.io/ipfs/Qma3Dy3mPusbRJrjJDbRuJPC1ohNF3qzi9x5teS4zNJ1WU
      keywords: Algorithmic self-assembly, computational geometry

    - name: Luis Barba
      description: >
        Postdoc at [ETH Zürich](https://www.ethz.ch/en.html), Switzerland,
        working in the group of [Professor Emo
        Welzl](https://www.inf.ethz.ch/personal/emo).
        Former PhD student.
      webpage: http://cglab.ca/~lfbarba
      email: luis.barba@inf.ethz.ch
      image: https://ipfs.io/ipfs/QmQSh1RyUxB9wn6rgBPq1rgka4NEMJXLYCQjAqyszf2yL6

    - name: Vissarion Fisikopoulos
      description: >
        Senior software engineer at [Oracle](https://www.oracle.com), working on development of
        geometric algorithms for GIS in
        [Boost.Geometry](http://www.boost.org/doc/libs/1_62_0/libs/geometry/doc/html/index.html)
        to support [MySQL](https://www.mysql.com). Former Postdoc.
      image: https://ipfs.io/ipfs/QmYJjzzbsfR6d9UXpAwRfMqscVTTGRqLvDedfxo5YKwhJV
      webpage: https://vissarion.github.io
      keywords: Discrete geometry, polyhedral combinatorics
      email: vissarion.fysikopoulos@oracle.com

    - name: Eglantine Camby
      description: >
        Junior researcher as a postdoc from the
        [Computer Science Department](http://www.ulb.ac.be/facs/sciences/info)
        at the [Université libre de
        Bruxelles (ULB)](http://www.ulb.ac.be) in Belgium, under the supervision
        of [Martine Labbé](http://homepages.ulb.ac.be/~mlabbe).
        Currently, one-year visitor in [HEC
        Montréal](http://www.hec.ca) and [GERAD](https://www.gerad.ca/fr), in Canada,
        under the supervision of
        [Gilles Caporossi](http://www.hec.ca/profs/gilles.caporossi.html).
        Former PhD student.
      webpage: http://homepages.ulb.ac.be/~ecamby
      email: Eglantine.Camby@ulb.ac.be
      image: https://ipfs.io/ipfs/QmdKtGVRr12jYfyo3g9ARMgG8bizwY48MEMWbiPrXdGL8m

    - name: Michael Payne
      description: Lecturer, [La Trobe University](https://www.latrobe.edu.au). Former Postdoc.
      webpage: http://www.ms.unimelb.edu.au/~mspayne
      email: mpayne@ulb.ac.be
      keywords: Discrete geometry, geometric graph theory.
      image: https://ipfs.io/ipfs/QmYFjdDaxBiE9P1eGdBMfJKCS2pmKTjQEvFM9QFLFGt2Vw

    - name: Greg Aloupis
      description: >
        Industry Professor, [New York University](https://www.nyu.edu).
        Former Chargé de recherches du FNRS (FNRS Postdoctoral Researcher).
      keywords:  Computational geometry
      email: aloupis.greg@gmail.com
      image: https://ipfs.io/ipfs/Qmbe1zyXob1meeS9TdeAhBrrcbaesC4YP6rVrg833aFVvn
      webpage: http://cg.scs.carleton.ca/~greg

    - name: Matias Korman
      description: Visiting Assistant Professor at [Tufts](https://www.tufts.edu). Former Postdoc.
      keywords: >
        Geometric shortest path planning,
        Memory constrained algorithms,
        Battery management in ad-hoc networks.
      email: Matias.Korman@tufts.edu
      image: https://ipfs.io/ipfs/QmTXVFvCYNcZS2eWLwcc5VM6LMKrpGUzjvHKN3cJFXHjhX
      webpage: https://engineering.tufts.edu/people/faculty/matias-korman

    - name: Marcin Kaminski
      description: Chargé de recherches du FNRS (FNRS Postdoctoral Researcher).
      keywords: Graph theory, Algorithms.
      email: Marcin.Kaminski@ulb.ac.be
      image: https://ipfs.io/ipfs/QmWbYroiFT1BNXGir4oC3o5PjmH6JdvGy4Q3m25UzXyUN2
      webpage: http://rutcor.rutgers.edu/~mkaminski

    - name: Pegah Kamousi
      keywords: Probabilistic Optimization, Computational Geometry
      email: pegahk@gmail.com
      image: https://ipfs.io/ipfs/QmXcPPMKK1Wv6SVDHjZcLEddseZE2PkHgwGSBNaZJKcVg3
      description: Former Postdoc

    - name: Maria Saumell
      keywords: Computational Geometry
      email: maria.saumell.m@gmail.com
      image: https://ipfs.io/ipfs/Qmb7TNtAn8kPDvdZUc8Mp7tamRGZwoNxACu16ZUV6BNAjy
      webpage: http://home.zcu.cz/~saumell

    - name: Luca Castelli-Aleardi
      image: https://ipfs.io/ipfs/QmaevgY4VQPMT7MFY9Y7qgh3BVDT4YqdaMS7G6qM13Kb2p
      webpage: http://www.lix.polytechnique.fr/~amturing

    - name: Nathann Cohen
      image: https://ipfs.io/ipfs/QmcsUso3ECFPJ44d5ixq368Sfvc6ApixeijRxqY2sqTjNT
      webpage: http://steinertriples.fr/ncohen

    - name: Raphael Jungers
      image: https://ipfs.io/ipfs/QmeDUo762Em6gXxfJeSsJ9HLSCYjWVxpgFpN6dCaX3dYyD
      webpage: http://perso.uclouvain.be/raphael.jungers

    - name: Perouz Taslakian
      image: https://ipfs.io/ipfs/QmSPAbEVnx96bhkpeYCxFFF72f8GE5DhQKWoYvtFnVeMNN
      webpage: http://homepages.ulb.ac.be/~ptaslaki

    - name: Karim Douïeb
      image: https://ipfs.io/ipfs/QmYJESNmdhznXMGXCgCPvoJWJrX1b1Uf1oH6odWsiqhYhS
      webpage: http://www.ulb.ac.be/di/algo/kdouieb
      description: Co-Founder - [Jetpack.AI](https://jetpack.ai). Former PhD student.


  visitors:

    - name: Lena Yuditsky
      image: https://ipfs.io/ipfs/QmQ5bCNhzCbjeN7p1kw82wj6fiwiTQv6V3W5TJQwhDXtEk
      visiting: October 2018
      webpage: http://www.math.kit.edu/iag6/~yuditsky

    - name: Bartosz Walczak
      image: https://ipfs.io/ipfs/QmRPxP3H4ttoKn6xp9ucuirLMCDhS56Ct7e6KSkzXkSQuy
      visiting: August 2018
      webpage: http://www.tcs.uj.edu.pl/walczak

    - name: Riko Jacob
      image: https://ipfs.io/ipfs/QmW6VjL7rVG9voe4KWqjwhbbzq2KAUjfrAXprXja6CoR1M
      visiting: July 2018
      webpage: https://www.itu.dk/people/rikj

    - name: Konstantinos A. Tsakalidis
      image: https://ipfs.io/ipfs/QmeUJeUwtBWw8FwzXqQKnBTMnU7tiD4Qqvw82sCQvW1YQm
      visiting: July 2018
      webpage: http://www.madalgo.au.dk/~tsakalid

    - name: Nodari Sitchinava
      image: https://ipfs.io/ipfs/QmWwf8FjRDnGU5BesqTZGLx8AZMJn6JMC38JNpVvuBKGTW
      visiting: July 2018
      webpage: https://www2.hawaii.edu/~nodari

    - name: Torsten Ueckerdt
      image: https://ipfs.io/ipfs/QmW4D8StwEbiKqa7DrRcVaNf19PbetQwoX75vu8UGQT5bN
      visiting: April 2018
      webpage: http://www.math.kit.edu/iag6/~ueckerdt/en

    - name: Kolja Knauer
      image: https://ipfs.io/ipfs/QmP65gzE9crL55jBy9HiXcK97jtywuJMQQKtp8PJZjE6cE
      visiting: April 2018
      webpage: http://pageperso.lif.univ-mrs.fr/~kolja.knauer

    - name: Piotr Micek
      image: https://ipfs.io/ipfs/QmdFTPsqp6tWKQS9BPHb9e9ysiSHstEr27SkaK4K57opWk
      visiting: April 2018
      webpage: http://page.math.tu-berlin.de/~micek

    - name: Sander Gribling
      image: https://ipfs.io/ipfs/QmNu8T9ewY2xsYrLRtQPE3FDq6gEq3SzmArrtSCQLE5KxZ
      visiting: April 2018
      webpage: https://www.cwi.nl/people/sander-gribling

    - name: Natalia Garcia Colin
      image: https://ipfs.io/ipfs/QmUx2U3n7NwsNtCZdqpJUjDeAtm1qENF2hNP1ApX4eQA9D
      visiting: March - April 2018
      webpage: https://www.infotec.mx/es_mx/infotec/natalia_garcia_colin

    - name: Ahmad Abdi
      image: https://ipfs.io/ipfs/QmeRGbPgJbBCWkfhGKAbtQ6KazLtHK8W8M4y2dDqbQ9PmP
      visiting: March 2018
      webpage: https://www.math.uwaterloo.ca/~a3abdi

    - name: Mikkel Abrahamsen
      image: https://ipfs.io/ipfs/QmUm9Gh6nh7We21fBkLN57m9RT7YC61RPWzW8KvgWh6BUX
      visiting: February 2018
      webpage: http://diku.dk/english/staff/?pure=en/persons/289414

    - name: Grigorios Koumoutsos
      image: https://ipfs.io/ipfs/QmVZ8VgLCg3yp9XrWmLW4NM79n8yww53wLDvq8Z9c2FVoh
      visiting: February 2018
      webpage: https://www.win.tue.nl/~gkoumout

    - name: Thatchapol Saranurak
      image: https://ipfs.io/ipfs/QmQgGmTcCcs2TTaGz9jaMwFbTvhFG33FZymuoxTDFr3WXW
      visiting: January 2018
      webpage: https://sites.google.com/site/thsaranurak

    - name: Luis Barba
      image: https://ipfs.io/ipfs/QmQSh1RyUxB9wn6rgBPq1rgka4NEMJXLYCQjAqyszf2yL6
      visiting: November 2017
      webpage: http://cglab.ca/~lfbarba

    - name: Wouter Cames van Batenburg
      image: https://ipfs.io/ipfs/QmNycDvxe1WXd2prsmJjLMggrnSFj8LSz3hDY35jRQ5ARB
      visiting: November 2017
      webpage: https://www.math.ru.nl/~woutercvb
