baseurl: https://algo.ulb.be/
title: Algorithms Research Group (ULB)
theme: hugo-creative-portfolio-theme
languageCode: en-us
# Enable comments by entering your Disqus shortname
#disqusShortname:
# Enable Google Analytics by entering your tracking code
#googleAnalytics:

sitemap:
  changefreq: monthly
  priority: 1

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: blue
  description: Website for the algo group @ ULB.
  #copyright:
  mobileNavAbout: >
    <b><a href="http://algo.ulb.be">Algorithms Research Group</a></b><br>
    <a href="http://www.ulb.ac.be/facs/sciences/info/index-en.html">Computer Science Department</a><br>
    <a href="http://www.ulb.ac.be/facs/sciences">Faculté des Sciences</a><br>
    <a href="http://www.ulb.ac.be">Université libre de Bruxelles (ULB)</a><br>
    Campus de la Plaine, CP 212<br>
    B-1050 Brussels, Belgium<br>
  sidebarAbout:
    - >
      <b><a href="http://algo.ulb.be">Algorithms Research Group</a></b><br>
      <a href="http://www.ulb.ac.be/facs/sciences/info/index-en.html">Computer Science Department</a><br>
      <a href="http://www.ulb.ac.be/facs/sciences">Faculté des Sciences</a><br>
      <a href="http://www.ulb.ac.be">Université libre de Bruxelles (ULB)</a><br>
      Campus de la Plaine, CP 212<br>
      B-1050 Brussels, Belgium<br>
    - >
        <img src="/img/delaunay.png" alt="" class="img-responsive">
    - >
      Keywords: Discrete and computational geometry,
      algorithmic and structural graph theory,
      combinatorial optimization, data structures.
    #- >
      #Currently funded research projects:
      #EUROCORES EuroGIGA <a href="http://eurogiga-compose.eu/about.php">ComPoSe</a> and
      #<a href="http://eurogiga.inf.fu-berlin.de/w/VORONOI/">VORONOI</a>,
      #and ARC <a href="http://www.ulb.ac.be/recherche/presentation/fr-arccerf.html">COPHYMA</a>.

  # Contact page
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #email:

  navlinks:
    # Nav links in the side bar
    - name: "The team"
      url: ""

    - name: "Alumni"
      url: "alumni/"

    - name: "Visitors"
      url: "visitors/"

  extlinks:
    # External nav links in the side bar
    - name: "Algo Lunch"
      url: "http://www.ulb.ac.be/di/algo/gjoret/algolunch.html"

  #social:
    #facebook:
    #googleplus:
    #email:
    #twitter:
    #linkedin:
    #stackoverflow:
    #instagram:
    #github:

  team:

    # Permanent staff

    - name: Jean Cardinal
      image: /img/team/jean-cardinal.jpg
      webpage: http://www.ulb.ac.be/di/algo/jcardin
      description: Professor
      keywords: Discrete and computational geometry, graphs, information theory.
      office: 2.O8.112
      phone: 02/650.5608
      email: jcardin@ulb.ac.be

    - name: Samuel Fiorini
      image: /img/team/samuel-fiorini.jpg
      webpage: http://homepages.ulb.ac.be/~sfiorini
      description: Professor (Math Department)
      keywords: Combinatorial optimization, polyhedral combinatorics, graph theory.
      email: sfiorini@ulb.ac.be

    - name: Gwenaël Joret
      image: /img/team/gwenael-joret.jpg
      webpage: http://www.ulb.ac.be/di/algo/gjoret
      description: Assistant Professor
      keywords: Graph theory, combinatorial optimization, approximation algorithms.
      office: 2.O8.111
      phone: 02/650.5759
      email: gjoret@ulb.ac.be

    - name: Stefan Langerman
      image: /img/team/stefan-langerman.jpg
      webpage: https://algo.ulb.be/sl
      description: Directeur de recherches (FNRS Research Director)
      keywords: Computational geometry, data structures.
      office: 2.O8.113
      phone: 02/650.5928
      email: stefan.langerman@ulb.ac.be

    - name: John Iacono
      image: /img/team/john-iacono.jpg
      webpage: http://johniacono.com
      description: Professor
      keywords: Data structures, computational geometry.
      office: 2.O8.114
      email: ulb@johniacono.com

    - name: Guy Louchard
      image: /img/team/guy-louchard.jpg
      webpage: http://www.ulb.ac.be/di/mcs/louchard
      description: I am now retired so I can devote (almost) all my time to research.
      keywords: Probabilistic techniques
      office: 2.N8.206
      phone: 02/650.5613
      email: louchard@ulb.ac.be

    # Postdocs

    - name: Elena Khramtcova
      image: /img/team/elena-khramtcova.jpg
      webpage: http://homepages.ulb.ac.be/~ekhramtc
      description: Postdoc
      keywords: Computational Geometry, Algorithms, Data Structures, Voronoi diagrams.
      office: 2.O8.214
      email: elena.khramtcova@ulb.ac.be

    - name: Varunkumar Jayapaul
      description: Postdoc
      image: /img/team/varunkumar-jayapaul.jpg
      office: 2.O8.214
      email: varunkumarj@gmail.com

    - name: Suman Bala
      description: Postdoc (Algo & QualSec)
      image: /img/team/suman-bala.png
      email: suman1005@gmail.com

    - name: Wouter Cames van Batenburg
      image: https://www.math.ru.nl/~woutercvb/wouter_compr.jpg
      webpage: https://www.math.ru.nl/~woutercvb
      description: Postdoc
      keywords: >
        percolation theory, coloring problems, extremal combinatorics,
        high-dimensional percolation, Last Passage Percolation,
        coloring and packing of graphs.

    - name: Grigorios Koumoutsos
      description: Future Postdoc
      image: /img/team/grigorios-koumoutsos.jpg
      webpage: https://www.win.tue.nl/~gkoumout

    - name: Ben Karsin
      description: Future Postdoc
      image: /img/team/ben-karsin.jpg
      webpage: https://benkarsin.com

    - name: Tillmann Miltzow
      image: /img/team/tillmann-miltzow.jpg
      webpage: https://sites.google.com/site/tillshome
      description: Postdoc (Math Department)
      keywords: Computational geometry.
      email: t.miltzow@googlemail.com

    - name: Tony Huynh
      description: Postdoc (Math Department)
      image: /img/team/tony-huynh.jpg
      webpage: https://sites.google.com/site/matroidintersection

    - name: Krystal Guo
      description: Postdoc (Math Department)
      image: /img/team/krystal-guo.jpg
      webpage: https://simons.berkeley.edu/people/krystal-guo

    # PhD students

    - name: Keno Merckx
      image: /img/team/keno-merckx.jpg
      webpage: http://homepages.ulb.ac.be/~kmerckx
      description: PhD student
      keywords: Graphs
      email: kmerckx@ulb.ac.be

    - name: Aurélien Ooms
      description: PhD student
      image: /img/team/aurelien-ooms.jpg
      webpage: http://homepages.ulb.ac.be/~aureooms
      keywords: "Computational Complexity: Data Structures, Algorithms, Computational Geometry."
      office: 2.O8.214
      email: aureooms@ulb.ac.be

    - name: Marco Macchia
      description: PhD student (Math Department)
      image: /img/team/marco-macchia.jpg
      webpage: http://homepages.ulb.ac.be/~mmacchia

    - name: Carole Muller
      description: PhD student (Math Department)
      image: http://student.ulb.ac.be/~camuller/images/Carole_Muller.png
      webpage: http://student.ulb.ac.be/~camuller

    - name: Matthew Drescher
      description: PhD student (Math Department)
      image: https://i.ytimg.com/vi/U9sR024xM_0/maxresdefault.jpg

    # External members

    - name: Sébastien Collette
      image: /img/team/sebastien-collette.jpg
      webpage: http://www.ulb.ac.be/di/algo/secollet
      description: Visiting professor (Maître de Conférence) at ULB. Consultant at Synapsis.
      keywords: Computational geometry, data structures.
      email: sebastien.collette@ulb.ac.be


  alumni:

    - name: Udo Hoffmann
      image: /img/team/udo-hoffmann.jpg
      webpage: https://udohoffmann.bitbucket.io
      description: Former Postdoc
      keywords: Combinatorial geometry.
      email: udo.hoffmann@ulb.ac.be

    - name: Irina Kostitsyna
      image: /img/team/irina-kostitsyna.jpg
      webpage: http://homepages.ulb.ac.be/~ikostits
      description: Former Postdoc
      keywords: "Computational Geometry: Polygons."
      email: irina.kostitsyna@ulb.ac.be

    - name: Andrew Winslow
      description: >
        Assistant Professor at the [Computer Science
        Department](http://www.utrgv.edu/csci) at the [University of Texas Rio
        Grande Valley](http://www.utrgv.edu). Former Postdoc.
      webpage: http://andrewwinslow.com
      email: andrew.winslow+ulb@gmail.com
      image: /img/alumni/andrew-winslow.png
      keywords: Algorithmic self-assembly, computational geometry

    - name: Luis Barba
      description: >
        Postdoc at [ETH Zürich](https://www.ethz.ch/en.html), Switzerland,
        working in the group of [Professor Emo
        Welzl](https://www.inf.ethz.ch/personal/emo).
        Former PhD student.
      webpage: http://cglab.ca/~lfbarba
      email: luis.barba@inf.ethz.ch
      image: /img/alumni/luis-barba.jpg

    - name: Vissarion Fisikopoulos
      description: >
        Senior software engineer at [Oracle](https://www.oracle.com), working on development of
        geometric algorithms for GIS in
        [Boost.Geometry](http://www.boost.org/doc/libs/1_62_0/libs/geometry/doc/html/index.html)
        to support [MySQL](https://www.mysql.com). Former Postdoc.
        image: /img/alumni/vissarion-fisikopoulos.jpg
      webpage: https://vissarion.github.io
      keywords: Discrete geometry, polyhedral combinatorics
      email: vissarion.fysikopoulos@oracle.com

    - name: Eglantine Camby
      description: >
        Junior researcher as a postdoc from the
        [Computer Science Department](http://www.ulb.ac.be/facs/sciences/info)
        at the [Université libre de
        Bruxelles (ULB)](http://www.ulb.ac.be) in Belgium, under the supervision
        of [Martine Labbé](http://homepages.ulb.ac.be/~mlabbe).
        Currently, one-year visitor in [HEC
        Montréal](http://www.hec.ca) and [GERAD](https://www.gerad.ca/fr), in Canada,
        under the supervision of
        [Gilles Caporossi](http://www.hec.ca/profs/gilles.caporossi.html).
        Former PhD student.
      webpage: http://homepages.ulb.ac.be/~ecamby
      email: Eglantine.Camby@ulb.ac.be
      image: /img/alumni/eglantine-camby.png

    - name: Michael Payne
      description: Former Postdoc
      webpage: http://www.ms.unimelb.edu.au/~mspayne
      email: mpayne@ulb.ac.be
      keywords: Discrete geometry, geometric graph theory.
      image: /img/alumni/michael-payne.jpg

    - name: Greg Aloupis
      description: Chargé de recherches du FNRS (FNRS Postdoctoral Researcher).
      keywords:  Computational geometry
      email: aloupis.greg@gmail.com
      image: /img/alumni/greg-aloupis.jpg
      webpage: http://cg.scs.carleton.ca/~greg

    - name: Matias Korman
      description: >
        Assistant professor at
        [Tokuyama Laboratory](http://www.dais.is.tohoku.ac.jp/index_e.html)
        within [Tohoku University](http://www.tohoku.ac.jp/en).
      keywords: >
        Geometric shortest path planning,
        Memory constrained algorithms,
        Battery management in ad-hoc networks.
      email: mati@dais.is.tohoku.ac.jp
      image: /img/alumni/matias-korman.png
      webpage: http://www.dais.is.tohoku.ac.jp/~mati

    - name: Marcin Kaminski
      description: Chargé de recherches du FNRS (FNRS Postdoctoral Researcher).
      keywords: Graph theory, Algorithms.
      email: Marcin.Kaminski@ulb.ac.be
      image: /img/alumni/marcin-kaminski.jpg
      webpage: http://rutcor.rutgers.edu/~mkaminski

    - name: Pegah Kamousi
      keywords: Probabilistic Optimization, Computational Geometry
      email: pegahk@gmail.com
      image: /img/alumni/pegah-kamousi.jpg
      description: Former Postdoc

    - name: Maria Saumell
      keywords: Computational Geometry
      email: maria.saumell.m@gmail.com
      image: /img/alumni/maria-saumell.jpg
      webpage: http://home.zcu.cz/~saumell

    - name: Luca Castelli-Aleardi
      image: /img/alumni/luca-castelli-aleardi.jpg
      webpage: http://www.lix.polytechnique.fr/~amturing

    - name: Nathann Cohen
      image: /img/alumni/nathann-cohen.jpg
      webpage: http://steinertriples.fr/ncohen

    - name: Raphael Jungers
      image: /img/alumni/raphael-jungers.jpg
      webpage: http://perso.uclouvain.be/raphael.jungers

    - name: Perouz Taslakian
      image: /img/alumni/perouz-taslakian.jpg
      webpage: http://homepages.ulb.ac.be/~ptaslaki

    - name: Karim Douïeb
      image: /img/alumni/karim-douieb.jpg
      webpage: http://www.ulb.ac.be/di/algo/kdouieb


  visitors:

    - name: Torsten Ueckerdt
      image: http://www.math.kit.edu/iag6/~ueckerdt/media/june09.jpg
      visiting: 2018-04-23 - 2018-04-27
      webpage: http://www.math.kit.edu/iag6/~ueckerdt/en

    - name: Kolja Knauer
      image: http://pageperso.lif.univ-mrs.fr/~kolja.knauer/IMG_7382.JPG
      visiting: 2018-04-23 - 2018-04-27
      webpage: http://pageperso.lif.univ-mrs.fr/~kolja.knauer

    - name: Piotr Micek
      image: https://www.math.tu-berlin.de/fileadmin/_processed_/e/e1/csm_piotr_1e7cc348f0.jpg
      visiting: 2018-04-23 - 2018-04-27
      webpage: http://page.math.tu-berlin.de/~micek

    - name: Sander Gribling
      image: https://www.cwi.nl/intranet/faces/2851.jpg
      visiting: 2018-04-09 - 2018-04-13
      webpage: https://www.cwi.nl/people/sander-gribling

    - name: Natalia Garcia Colin
      image: https://www.infotec.mx/work/models/infotec/design_2015/images/fotos_investigadores/Natalia-Garcia-Colin.jpg
      visiting: 2018-03-06 - 2018-04-13
      webpage: https://www.infotec.mx/es_mx/infotec/natalia_garcia_colin
